### PR TITLE
Fix xqanalyze compatibility with cypress

### PR DESCRIPTION
**Pull request by bdero**

### CODE REVIEW

**Comment by bdero** [comment]
The failures are due to a single pylint failure in `xsiftx/web.py`, and don't have to do with this change.

**Comment by pdpinch** [comment]
Does this fix the failing sifter?

**Comment by bdero** [comment]
There are multiple failing sifters. This fixes xqanalyze, which generates a grade dump in the form of a zip. I discovered the cypress incompatibilities when Ana asked for a dump in light of the CSV generation not working (from dump_grades).

xqanalyze hooks the edX codebase and extracts student data straight out of the StudentModule model. dump_grades runs the dump_grades django management command, which is broken: https://openedx.atlassian.net/browse/CRI-40

**Comment by pdpinch** [comment]
:+1:

**Pull request merged**
